# Regression Adjustments

## Load Data

In [51]:
import os
import pandas as pd
import numpy as np

os.chdir('/Users/janlinzner/Projects/Master-Thesis-Spatial-Proximity-Venture-Capital')

In [52]:
data = pd.read_csv('data/sets-for-r/data.csv')

## Outlier cutting

In [53]:
chosen_variables = ['number_of_founders', 'avg_age_of_seed_investors', 'total_seed_funding_m']

lower_quantile = data[chosen_variables].quantile(0.01)
upper_quantile = data[chosen_variables].quantile(0.99)

for variable in chosen_variables:
    lower_bound = lower_quantile[variable]
    upper_bound = upper_quantile[variable]
    data = data[(data[variable] >= lower_bound) & (data[variable] <= upper_bound)]

## Kilometer variables in 1000km

In [54]:
variables_to_divide = [
    'distance_to_hub',
    'avg_seed_investor_distance',
    'minimum_seed_vc_distance',
    'max_seed_investor_distance',
    'minimum_seed_vc_distance_non_lead',
    'avg_seed_vc_distance_non_lead',
    'maximum_seed_vc_distance_non_lead',
    'minimum_lead_seed_vc_distance',
    'avg_lead_seed_vc_distance',
    'maximum_lead_seed_vc_distance',
    'avg_seed_investor_pairwise_distance',
    'min_seed_investor_pairwise_distance',
    'max_seed_investor_pairwise_distance'
]

for variable in variables_to_divide:
    if variable in data.columns:
        data[variable] = data[variable] / 1000

## Save overall set

In [55]:
data.to_csv('data/sets-for-r/regression_sets/df_europe.csv', index=False)

In [56]:
data

,company_id,organization_name,organization_name_url,headquarters_country,latitude,longitude,founded_year,number_of_founders,b2b_binary,hub_binary,...,exit_binary,funding_success,post_seed_funding,exit_funding_success,exit_round_success,success,exit_date,years_to_exit,peer_coinv_top20_threshold,peer_portfolio_top20_threshold
0,17335,Dopplr,https://www.crunchbase.com/organization/dopplr,United Kingdom,51.489334,-0.144055,2007,5.0,False,True,...,True,False,False,True,True,True,2009-09-23,2.0,45.0,65.0
1,10067,SCHAD,https://www.crunchbase.com/organization/schad,Germany,51.177660,14.424888,2007,1.0,True,False,...,False,False,True,False,True,True,NaN,NaN,0.0,0.0
2,2060,Talentsoft,https://www.crunchbase.com/organization/talent...,France,48.835665,2.240206,2007,3.0,True,True,...,True,True,True,True,True,True,2021-04-12,14.0,28.0,37.0
3,5960,Cleveron,https://www.crunchbase.com/organization/cleveron,Estonia,58.364540,25.587807,2007,2.0,True,False,...,False,False,False,False,False,False,NaN,NaN,0.0,0.0
4,6903,flowww,https://www.crunchbase.com/organization/flowww...,Spain,40.423728,-3.689904,2007,2.0,True,True,...,False,False,True,False,True,True,NaN,NaN,8.0,14.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11081,13073,PROPERENTY,https://www.crunchbase.com/organization/proper...,Lithuania,54.687046,25.282911,2020,2.0,True,False,...,False,False,False,False,False,False,NaN,NaN,8.0,21.0
11082,13044,Reekon,https://www.crunchbase.com/organization/reekon,Lithuania,54.687046,25.282911,2020,2.0,True,False,...,False,False,False,False,False,False,NaN,NaN,8.0,21.0
11083,666,Lassie,https://www.crunchbase.com/organization/lassie,Sweden,59.325117,18.071093,2020,3.0,False,True,...,False,True,True,True,True,True,NaN,NaN,12.0,18.2
11084,1746,Patron GO,https://www.crunchbase.com/organization/patron-go,Czech Republic,50.083330,14.466670,2020,2.0,False,True,...,False,False,False,False,False,False,NaN,NaN,2.6,6.0
11085,2962,Cycloid,https://www.crunchbase.com/organization/cycloid,France,48.853495,2.348391,2020,1.0,True,True,...,False,False,True,False,True,True,NaN,NaN,28.0,37.0

## Country sets

In [57]:
country_dataframes = {country: data[data['headquarters_country'] == country] for country in data['headquarters_country'].unique()}

df_ger = country_dataframes['Germany']
df_uk = country_dataframes['United Kingdom']
df_fr = country_dataframes['France']
df_ita = country_dataframes['Italy']
df_sp = country_dataframes['Spain']
df_nl = country_dataframes['The Netherlands']
df_be = country_dataframes['Belgium']
df_nordics = pd.concat([country_dataframes['Denmark'], 
                        country_dataframes['Finland'], 
                        country_dataframes['Norway'],
                        country_dataframes['Sweden']])
df_east = pd.concat([country_dataframes['Czech Republic'], 
                     country_dataframes['Latvia'], 
                     country_dataframes['Poland'], 
                     country_dataframes['Slovakia (Slovak Republic)'], 
                     country_dataframes['Estonia'], 
                     country_dataframes['Lithuania'], 
                     country_dataframes['Hungary']])

df_dach = pd.concat([country_dataframes['Germany'], 
                     country_dataframes['Austria'], 
                     country_dataframes['Switzerland']])

df_big3 = pd.concat([country_dataframes['Germany'], 
                     country_dataframes['United Kingdom'], 
                     country_dataframes['France']])

In [58]:
dataframes_to_save = {
    'df_ger': df_ger,
    'df_uk': df_uk,
    'df_fr': df_fr,
    'df_ita': df_ita,
    'df_sp': df_sp,
    'df_nl': df_nl,
    'df_be': df_be,
    'df_nordics': df_nordics,
    'df_east': df_east,
    'df_dach': df_dach,
    'df_big3': df_big3
}

for name, dataframe in dataframes_to_save.items():
    dataframe.to_csv(f'data/sets-for-r/regression_sets/{name}.csv', index=False)

## Sector Datasets

In [59]:
sector_columns = [
    'energy', 'materials', 'industrials', 'consumer_discretionary', 'consumer_staples', 
    'health_care', 'financials', 'information_technology', 'communication_services', 
    'utilities', 'real_estate', 'other'
]

sector_datasets = {sector: data[data[sector] == True] for sector in sector_columns}

In [60]:
df_energy = sector_datasets['energy']
df_materials = sector_datasets['materials']
df_industrials = sector_datasets['industrials']
df_consumer_discretionary = sector_datasets['consumer_discretionary']
df_consumer_staples = sector_datasets['consumer_staples']
df_health_care = sector_datasets['health_care']
df_financials = sector_datasets['financials']
df_information_technology = sector_datasets['information_technology']
df_communication_services = sector_datasets['communication_services']
df_utilities = sector_datasets['utilities']
df_real_estate = sector_datasets['real_estate']
df_other = sector_datasets['other']

In [61]:
for sector, dataframe in sector_datasets.items():
    dataframe.to_csv(f'data/sets-for-r/regression_sets/df_{sector}.csv', index=False)

In [62]:
data

,company_id,organization_name,organization_name_url,headquarters_country,latitude,longitude,founded_year,number_of_founders,b2b_binary,hub_binary,...,exit_binary,funding_success,post_seed_funding,exit_funding_success,exit_round_success,success,exit_date,years_to_exit,peer_coinv_top20_threshold,peer_portfolio_top20_threshold
0,17335,Dopplr,https://www.crunchbase.com/organization/dopplr,United Kingdom,51.489334,-0.144055,2007,5.0,False,True,...,True,False,False,True,True,True,2009-09-23,2.0,45.0,65.0
1,10067,SCHAD,https://www.crunchbase.com/organization/schad,Germany,51.177660,14.424888,2007,1.0,True,False,...,False,False,True,False,True,True,NaN,NaN,0.0,0.0
2,2060,Talentsoft,https://www.crunchbase.com/organization/talent...,France,48.835665,2.240206,2007,3.0,True,True,...,True,True,True,True,True,True,2021-04-12,14.0,28.0,37.0
3,5960,Cleveron,https://www.crunchbase.com/organization/cleveron,Estonia,58.364540,25.587807,2007,2.0,True,False,...,False,False,False,False,False,False,NaN,NaN,0.0,0.0
4,6903,flowww,https://www.crunchbase.com/organization/flowww...,Spain,40.423728,-3.689904,2007,2.0,True,True,...,False,False,True,False,True,True,NaN,NaN,8.0,14.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11081,13073,PROPERENTY,https://www.crunchbase.com/organization/proper...,Lithuania,54.687046,25.282911,2020,2.0,True,False,...,False,False,False,False,False,False,NaN,NaN,8.0,21.0
11082,13044,Reekon,https://www.crunchbase.com/organization/reekon,Lithuania,54.687046,25.282911,2020,2.0,True,False,...,False,False,False,False,False,False,NaN,NaN,8.0,21.0
11083,666,Lassie,https://www.crunchbase.com/organization/lassie,Sweden,59.325117,18.071093,2020,3.0,False,True,...,False,True,True,True,True,True,NaN,NaN,12.0,18.2
11084,1746,Patron GO,https://www.crunchbase.com/organization/patron-go,Czech Republic,50.083330,14.466670,2020,2.0,False,True,...,False,False,False,False,False,False,NaN,NaN,2.6,6.0
11085,2962,Cycloid,https://www.crunchbase.com/organization/cycloid,France,48.853495,2.348391,2020,1.0,True,True,...,False,False,True,False,True,True,NaN,NaN,28.0,37.0